name: Python Checks for Pull Requests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Black Lint
        uses: psf/black@stable
      - name: Setup python environment for flake8 check
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Same as in Dockerfile
      - name: flake8 Lint
        uses: py-actions/flake8@v2
      - name: Run pytest
        run: |
          python -m pip install pytest requests
          pytest
